name: build-cases
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 6 * * *'
jobs:
  get-cases-and-testing-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repo
        uses: actions/checkout@v2.3.4
      - name: Setup Python Environment
        uses: actions/setup-python@v2.2.2
      - name: Cache Python Environment
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mkdir dataset
      - name: Get national timeseries from djay/covidthailand
        working-directory: cases
        run: |
          python get_national_timeseries.py
      - name: Get testing data from the government database
        working-directory: testing
        run: |
          python get_lab_data.py
      - name: Build province and district cases
        working-directory: cases
        run: python build_province_and_district_cases.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cases
          path: |
            dataset/*.json
  commit-files-to-wiki:
    needs: [get-cases-and-testing-data]
    runs-on: ubuntu-latest
    steps:
      - name: Check Repo
        uses: actions/checkout@v2.3.4
      - name: Download Cases Artifacts
        uses: actions/download-artifact@v2
        with:
          name: cases
          path: wiki/cases
      - name: Setup Python Environment
        uses: actions/setup-python@v2.2.2
      - name: Cache Python Environment
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build province infection graphs
        working-directory: cases
        run: python build_province_graphs.py cases-only
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload json to wiki
        uses: noppakorn/external-repo-sync-action@v1
        with:
          source-directory: './wiki'
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
